name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory (debug)
        run: ls -l target/

      - name: Upload fat jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-TicTacToe-fat-jar
          path: target/*jar-with-dependencies.jar
